CREATE DATABASE IF NOT EXISTS mybooking9_2;
use mybooking9_2;


CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_FIRST_NAME VARCHAR(50),
    CUSTOMER_LAST_NAME VARCHAR(50),
    CUSTOMER_EMAIL_ADDRESS VARCHAR(100),
    CUSTOMER_PHONE_NUMBER VARCHAR(20),
    ADDRESS_STREET VARCHAR(100),
    ADDRESS_CITY VARCHAR(50),
    ADDRESS_STATE VARCHAR(50),
    ADDRESS_POSTAL_CODE VARCHAR(10),
    ADDRESS_COUNTRY VARCHAR(50),
    CUSTOMER_REGISTRATION_DATE DATE
);